=begin
#phishingapi

#Easily and directly scan and block phishing security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module CloudmersivePhishingDetectionApiClient
  # Request to detect phishing from an email
  class AdvancedEmailDetectionRequest
    # Email address of the sender
    attr_accessor :from_email_address

    # Email address of the recipient
    attr_accessor :to_email_address

    # Subject of the email
    attr_accessor :subject

    # Body of the email in HTML, or text
    attr_accessor :html_body

    # Allow email from low reputation senders and domains
    attr_accessor :allow_low_reputation_senders

    # True to allow sanctioned countries and certain known sanctioned entities, false otherwise (default)
    attr_accessor :allow_sanctioned

    attr_accessor :input_email_file

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'from_email_address' => :'FromEmailAddress',
        :'to_email_address' => :'ToEmailAddress',
        :'subject' => :'Subject',
        :'html_body' => :'HtmlBody',
        :'allow_low_reputation_senders' => :'AllowLowReputationSenders',
        :'allow_sanctioned' => :'AllowSanctioned',
        :'input_email_file' => :'InputEmailFile'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'from_email_address' => :'String',
        :'to_email_address' => :'String',
        :'subject' => :'String',
        :'html_body' => :'String',
        :'allow_low_reputation_senders' => :'BOOLEAN',
        :'allow_sanctioned' => :'BOOLEAN',
        :'input_email_file' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'FromEmailAddress')
        self.from_email_address = attributes[:'FromEmailAddress']
      end

      if attributes.has_key?(:'ToEmailAddress')
        self.to_email_address = attributes[:'ToEmailAddress']
      end

      if attributes.has_key?(:'Subject')
        self.subject = attributes[:'Subject']
      end

      if attributes.has_key?(:'HtmlBody')
        self.html_body = attributes[:'HtmlBody']
      end

      if attributes.has_key?(:'AllowLowReputationSenders')
        self.allow_low_reputation_senders = attributes[:'AllowLowReputationSenders']
      end

      if attributes.has_key?(:'AllowSanctioned')
        self.allow_sanctioned = attributes[:'AllowSanctioned']
      end

      if attributes.has_key?(:'InputEmailFile')
        self.input_email_file = attributes[:'InputEmailFile']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@input_email_file.nil? && @input_email_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        invalid_properties.push('invalid value for "input_email_file", must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@input_email_file.nil? && @input_email_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] input_email_file Value to be assigned
    def input_email_file=(input_email_file)
      if !input_email_file.nil? && input_email_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        fail ArgumentError, 'invalid value for "input_email_file", must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.'
      end

      @input_email_file = input_email_file
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          from_email_address == o.from_email_address &&
          to_email_address == o.to_email_address &&
          subject == o.subject &&
          html_body == o.html_body &&
          allow_low_reputation_senders == o.allow_low_reputation_senders &&
          allow_sanctioned == o.allow_sanctioned &&
          input_email_file == o.input_email_file
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [from_email_address, to_email_address, subject, html_body, allow_low_reputation_senders, allow_sanctioned, input_email_file].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CloudmersivePhishingDetectionApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
