=begin
#phishingapi

#Easily and directly scan and block phishing security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module CloudmersivePhishingDetectionApiClient
  # AI advanced phishing detection request
  class PhishingDetectionAdvancedRequest
    # Input text string to detect phishing against
    attr_accessor :input_string

    # Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
    attr_accessor :model

    # Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
    attr_accessor :custom_policy_id

    # Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.
    attr_accessor :provide_analysis_rationale

    # Optional: Type of text being analyzed. Must be one of: \"Text Message\", \"User Message\", \"Sales Lead\", \"Email Message\", \"Support Case\", \"Other\".
    attr_accessor :text_type

    # Optional: Name of the sender
    attr_accessor :from_name

    # Optional: Name of the recipient
    attr_accessor :to_name

    # Optional: Phone number of the sender
    attr_accessor :from_phone_number

    # Optional: Phone number of the recipient
    attr_accessor :to_phone_number

    # Optional: Email address of the sender
    attr_accessor :from_email_address

    # Optional: Email address of the recipient
    attr_accessor :to_email_address

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'input_string' => :'InputString',
        :'model' => :'Model',
        :'custom_policy_id' => :'CustomPolicyID',
        :'provide_analysis_rationale' => :'ProvideAnalysisRationale',
        :'text_type' => :'TextType',
        :'from_name' => :'FromName',
        :'to_name' => :'ToName',
        :'from_phone_number' => :'FromPhoneNumber',
        :'to_phone_number' => :'ToPhoneNumber',
        :'from_email_address' => :'FromEmailAddress',
        :'to_email_address' => :'ToEmailAddress'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'input_string' => :'String',
        :'model' => :'String',
        :'custom_policy_id' => :'String',
        :'provide_analysis_rationale' => :'BOOLEAN',
        :'text_type' => :'String',
        :'from_name' => :'String',
        :'to_name' => :'String',
        :'from_phone_number' => :'String',
        :'to_phone_number' => :'String',
        :'from_email_address' => :'String',
        :'to_email_address' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'InputString')
        self.input_string = attributes[:'InputString']
      end

      if attributes.has_key?(:'Model')
        self.model = attributes[:'Model']
      end

      if attributes.has_key?(:'CustomPolicyID')
        self.custom_policy_id = attributes[:'CustomPolicyID']
      end

      if attributes.has_key?(:'ProvideAnalysisRationale')
        self.provide_analysis_rationale = attributes[:'ProvideAnalysisRationale']
      end

      if attributes.has_key?(:'TextType')
        self.text_type = attributes[:'TextType']
      end

      if attributes.has_key?(:'FromName')
        self.from_name = attributes[:'FromName']
      end

      if attributes.has_key?(:'ToName')
        self.to_name = attributes[:'ToName']
      end

      if attributes.has_key?(:'FromPhoneNumber')
        self.from_phone_number = attributes[:'FromPhoneNumber']
      end

      if attributes.has_key?(:'ToPhoneNumber')
        self.to_phone_number = attributes[:'ToPhoneNumber']
      end

      if attributes.has_key?(:'FromEmailAddress')
        self.from_email_address = attributes[:'FromEmailAddress']
      end

      if attributes.has_key?(:'ToEmailAddress')
        self.to_email_address = attributes[:'ToEmailAddress']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          input_string == o.input_string &&
          model == o.model &&
          custom_policy_id == o.custom_policy_id &&
          provide_analysis_rationale == o.provide_analysis_rationale &&
          text_type == o.text_type &&
          from_name == o.from_name &&
          to_name == o.to_name &&
          from_phone_number == o.from_phone_number &&
          to_phone_number == o.to_phone_number &&
          from_email_address == o.from_email_address &&
          to_email_address == o.to_email_address
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [input_string, model, custom_policy_id, provide_analysis_rationale, text_type, from_name, to_name, from_phone_number, to_phone_number, from_email_address, to_email_address].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CloudmersivePhishingDetectionApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
