=begin
#phishingapi

#Easily and directly scan and block phishing security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersivePhishingDetectionApiClient::PhishingUrlResponseBatch
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PhishingUrlResponseBatch' do
  before do
    # run before each test
    @instance = CloudmersivePhishingDetectionApiClient::PhishingUrlResponseBatch.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhishingUrlResponseBatch' do
    it 'should create an instance of PhishingUrlResponseBatch' do
      expect(@instance).to be_instance_of(CloudmersivePhishingDetectionApiClient::PhishingUrlResponseBatch)
    end
  end
  describe 'test attribute "clean_result"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url_responses"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
