=begin
#phishingapi

#Easily and directly scan and block phishing security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersivePhishingDetectionApiClient::PhishingDetectionTextStringRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PhishingDetectionTextStringRequest' do
  before do
    # run before each test
    @instance = CloudmersivePhishingDetectionApiClient::PhishingDetectionTextStringRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhishingDetectionTextStringRequest' do
    it 'should create an instance of PhishingDetectionTextStringRequest' do
      expect(@instance).to be_instance_of(CloudmersivePhishingDetectionApiClient::PhishingDetectionTextStringRequest)
    end
  end
  describe 'test attribute "input_string"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "model"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "provide_analysis_rationale"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
