=begin
#phishingapi

#Easily and directly scan and block phishing security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersivePhishingDetectionApiClient::PhishingUrlBatchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PhishingUrlBatchApi' do
  before do
    # run before each test
    @instance = CloudmersivePhishingDetectionApiClient::PhishingUrlBatchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhishingUrlBatchApi' do
    it 'should create an instance of PhishingUrlBatchApi' do
      expect(@instance).to be_instance_of(CloudmersivePhishingDetectionApiClient::PhishingUrlBatchApi)
    end
  end

  # unit tests for phishing_url_advanced_batch_post
  # Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat.
  # Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
  # @param [Hash] opts the optional parameters
  # @option opts [PhishingUrlAdvancedRequestBatch] :body 
  # @return [PhishingUrlAdvancedResponseBatch]
  describe 'phishing_url_advanced_batch_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phishing_url_batch_post
  # Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat.
  # Uses AI and deterministic methods to detect if a URL is a phishing threat.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<PhishingUrlRequest>] :body 
  # @return [PhishingUrlResponseBatch]
  describe 'phishing_url_batch_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
