=begin
#phishingapi

#Easily and directly scan and block phishing security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersivePhishingDetectionApiClient::PhishingUrlApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PhishingUrlApi' do
  before do
    # run before each test
    @instance = CloudmersivePhishingDetectionApiClient::PhishingUrlApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhishingUrlApi' do
    it 'should create an instance of PhishingUrlApi' do
      expect(@instance).to be_instance_of(CloudmersivePhishingDetectionApiClient::PhishingUrlApi)
    end
  end

  # unit tests for phishing_url_advanced_post
  # Use advanced AI detection to determine if a URL is a known phishing threat
  # Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
  # @param [Hash] opts the optional parameters
  # @option opts [PhishingUrlAdvancedRequest] :body 
  # @return [PhishingUrlAdvancedResponse]
  describe 'phishing_url_advanced_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phishing_url_post
  # Use AI and deterministic detection to determine if a URL is a phishing threat
  # Uses AI and deterministic methods to detect if a URL is a phishing threat.
  # @param [Hash] opts the optional parameters
  # @option opts [PhishingUrlRequest] :body 
  # @return [PhishingUrlResponse]
  describe 'phishing_url_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
