=begin
#phishingapi

#Easily and directly scan and block phishing security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersivePhishingDetectionApiClient::PhishingDetectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PhishingDetectionApi' do
  before do
    # run before each test
    @instance = CloudmersivePhishingDetectionApiClient::PhishingDetectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhishingDetectionApi' do
    it 'should create an instance of PhishingDetectionApi' do
      expect(@instance).to be_instance_of(CloudmersivePhishingDetectionApiClient::PhishingDetectionApi)
    end
  end

  # unit tests for phishing_detect_email_advanced_post
  # Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
  # @param [Hash] opts the optional parameters
  # @option opts [AdvancedEmailDetectionRequest] :body Phishing detection request
  # @return [PhishingDetectionEmailAdvancedResponse]
  describe 'phishing_detect_email_advanced_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phishing_detect_file_advanced_post
  # Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :model 
  # @option opts [File] :input_file 
  # @return [PhishingDetectionAdvancedResponse]
  describe 'phishing_detect_file_advanced_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phishing_detect_file_post
  # Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :model Model to use; default setting is Advanced
  # @option opts [File] :input_file 
  # @return [PhishingDetectionResponse]
  describe 'phishing_detect_file_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phishing_detect_text_string_advanced_post
  # Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
  # @param [Hash] opts the optional parameters
  # @option opts [PhishingDetectionAdvancedRequest] :body Phishing detection request
  # @return [PhishingDetectionAdvancedResponse]
  describe 'phishing_detect_text_string_advanced_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
