=begin
#phishingapi

#Easily and directly scan and block phishing security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-phishing-detection-api-client/api_client'
require 'cloudmersive-phishing-detection-api-client/api_error'
require 'cloudmersive-phishing-detection-api-client/version'
require 'cloudmersive-phishing-detection-api-client/configuration'

# Models
require 'cloudmersive-phishing-detection-api-client/models/advanced_email_detection_request'
require 'cloudmersive-phishing-detection-api-client/models/advanced_url_detection_request'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_advanced_request'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_advanced_response'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_email_advanced_response'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_response'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_text_string_request'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_text_string_response'
require 'cloudmersive-phishing-detection-api-client/models/phishing_detection_url_advanced_response'
require 'cloudmersive-phishing-detection-api-client/models/unsafe_url_result'

# APIs
require 'cloudmersive-phishing-detection-api-client/api/phishing_detection_api'

module CloudmersivePhishingDetectionApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersivePhishingDetectionApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
