=begin
#phishingapi

#Easily and directly scan and block phishing security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-phishing-detection-api-client/api_client'
require 'cloudmersive-phishing-detection-api-client/api_error'
require 'cloudmersive-phishing-detection-api-client/version'
require 'cloudmersive-phishing-detection-api-client/configuration'

# Models
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_advanced_request'
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_advanced_request_batch'
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_advanced_response'
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_advanced_response_batch'
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_request'
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_response'
require 'cloudmersive-phishing-detection-api-client/models/phishing_url_response_batch'

# APIs
require 'cloudmersive-phishing-detection-api-client/api/phishing_url_api'
require 'cloudmersive-phishing-detection-api-client/api/phishing_url_batch_api'

module CloudmersivePhishingDetectionApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersivePhishingDetectionApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
